AWSTemplateFormatVersion: "2010-09-09"
Description: ECR repositories for frontend and backend Docker images

Parameters:
  environment:
    Description: Environment type
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
    Default: dev

  product:
    Description: Name of the product or part of the project
    Type: String
    Default: impressico

  service:
    Description: Name of the Service
    Type: String
    Default: ecr

Resources:
  # ── BACKEND REPO ──────────────────────────────────────────────────────────────
  backendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${environment}-${product}-backend
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: !Sub ${environment}-${product}-backend

  frontendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${environment}-${product}-frontend
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: !Sub ${environment}-${product}-frontend

Outputs:
  backendRepositoryName:
    Description: Backend ECR repository name
    Value: !Ref backendRepository
    Export:
      Name: !Sub "${environment}-${product}-backend-ecr"

  backendRepositoryUri:
    Description: Backend ECR repository URI
    Value: !GetAtt backendRepository.RepositoryUri
    Export:
      Name: !Sub "${environment}-${product}-backend-ecr-uri"

  backendRepositoryArn:
    Description: Backend ECR repository ARN
    Value: !GetAtt backendRepository.Arn
    Export:
      Name: !Sub "${environment}-${product}-backend-ecr-arn"

  frontendRepositoryName:
    Description: Frontend ECR repository name
    Value: !Ref frontendRepository
    Export:
      Name: !Sub "${environment}-${product}-frontend-ecr"

  frontendRepositoryUri:
    Description: Frontend ECR repository URI
    Value: !GetAtt frontendRepository.RepositoryUri
    Export:
      Name: !Sub "${environment}-${product}-frontend-ecr-uri"

  frontendRepositoryArn:
    Description: Frontend ECR repository ARN
    Value: !GetAtt frontendRepository.Arn
    Export:
      Name: !Sub "${environment}-${product}-frontend-ecr-arn"
