AWSTemplateFormatVersion: "2010-09-09"
Description: S3 bucket for EC2 termination backups (Lambda ships /var/log here before instance dies)

Parameters:
  environment:
    Description: Environment type
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
    Default: dev

  product:
    Description: Name of the product or part of the project
    Type: String
    Default: impressico

  service:
    Description: Name of the Service
    Type: String
    Default: s3

Resources:
  backupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${environment}-${product}-backups"
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldBackups
            Status: Enabled
            ExpirationInDays: 30 # delete backup archives after 30 days
      Tags:
        - Key: Name
          Value: !Sub ${environment}-${product}-backups
        - Key: environment
          Value: !Ref environment
        - Key: product
          Value: !Ref product

Outputs:
  backupBucketName:
    Description: Name of the S3 backup bucket
    Value: !Ref backupBucket
    Export:
      Name: !Sub "${environment}-${product}-backup-bucket"

  backupBucketArn:
    Description: ARN of the S3 backup bucket
    Value: !GetAtt backupBucket.Arn
    Export:
      Name: !Sub "${environment}-${product}-backup-bucket-arn"
