include:
  - local: ".gitlab-ci/templates/infrastructure.yml"
  - local: ".gitlab-ci/templates/application.yml"
  - local: ".gitlab-ci/templates/sam.yml"
  - local: ".gitlab-ci/templates/variables.yml"

default:
  tags:
    - pipvansh

workflow:
   rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    
stages:
  - infra-deploy
  - sam-deploy
  - app-deploy
