AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model (SAM) template describing your function.
Resources:
  devimpressicolambda:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      CodeUri: ./src
      Description: ""
      EphemeralStorage:
        Size: 512
      Handler: lambda_function.lambda_handler
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/dev-impressico-lambda
      MemorySize: 128
      PackageType: Zip
      RecursiveLoop: Terminate
      Runtime: python3.14
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      SnapStart:
        ApplyOn: None
      Tags:
        CreatedAt: "2026-06-02T09:07:00Z"
        CreatedBy: vansh.padia
      Timeout: 303
      Tracing: PassThrough
      Events:
        Trigger1Event:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.autoscaling
              detail-type:
                - EC2 Instance-terminate Lifecycle Action
              detail:
                AutoScalingGroupName:
                  - dev-impressico-asg
                LifecycleHookName:
                  - dev-impressico-termination-hook
