include:
  - local: ".gitlab-ci/templates/awscli.yml"

deploy_app_job:
  stage: app-deploy
  extends: .assume_role
  image:
    name: amazon/aws-cli:2.34.18
    entrypoint: [""]  
  script:
    - ./.gitlab-ci/scripts/ssmDeploy.sh
  rules:
    - if: '$PIPELINE_TYPE == "app"'
