---
Metadata:
  AWSToolsMetrics:
    IaC_Generator: "arn:aws:cloudformation:ap-south-1:313686187887:generatedTemplate/14e75ef3-ae8b-4d8c-af20-4510210d9efe"
Parameters:
  LambdaFunctionASGTerminationBackupCodeImageUri6HGXP:
    NoEcho: "true"
    Type: "String"
    Description:
      "URI of a [container image](https://docs.aws.amazon.com/lambda/latest/dg/lambda-images.html)\
      \ in the Amazon ECR registry."
  LambdaFunctionDevimpressicolambdaCodeS3BucketYWBwK:
    NoEcho: "true"
    Type: "String"
    Description:
      "An Amazon S3 bucket in the same AWS-Region as your function. The\
      \ bucket can be in a different AWS-account."
  LambdaFunctionDevimpressicolambdaCodeSourceKMSKeyArnabMyW:
    NoEcho: "true"
    Type: "String"
    Description:
      "The ARN of the KMSlong (KMS) customer managed key that's used to\
      \ encrypt your function's .zip deployment package. If you don't provide a customer\
      \ managed key, Lambda uses an [owned key](https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#aws-owned-cmk)."
  LambdaFunctionDevimpressicolambdaCodeImageUriJrShB:
    NoEcho: "true"
    Type: "String"
    Description:
      "URI of a [container image](https://docs.aws.amazon.com/lambda/latest/dg/lambda-images.html)\
      \ in the Amazon ECR registry."
  LambdaFunctionASGTerminationBackupCodeS3ObjectVersionDfNMe:
    NoEcho: "true"
    Type: "String"
    Description:
      "For versioned objects, the version of the deployment package object\
      \ to use."
  LambdaFunctionDevimpressicolambdaCodeS3Keyu3jbz:
    NoEcho: "true"
    Type: "String"
    Description: "The Amazon S3 key of the deployment package."
  LambdaFunctionDevimpressicolambdaCodeS3ObjectVersione07Si:
    NoEcho: "true"
    Type: "String"
    Description:
      "For versioned objects, the version of the deployment package object\
      \ to use."
  LambdaFunctionASGTerminationBackupCodeS3Buckettpomx:
    NoEcho: "true"
    Type: "String"
    Description:
      "An Amazon S3 bucket in the same AWS-Region as your function. The\
      \ bucket can be in a different AWS-account."
  LambdaFunctionASGTerminationBackupCodeZipFilenMJG1:
    NoEcho: "true"
    Type: "String"
    Description:
      "(Node.js and Python) The source code of your Lambda function. If\
      \ you include your function source inline with this parameter, CFN places it\
      \ in a file named ``index`` and zips it to create a [deployment package](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-package.html).\
      \ This zip file cannot exceed 4MB. For the ``Handler`` property, the first part\
      \ of the handler identifier must be ``index``. For example, ``index.handler``.\n\
      \  When you specify source code inline for a Node.js function, the ``index``\
      \ file that CFN creates uses the extension ``.js``. This means that Node.js\
      \ treats the file as a CommonJS module.\n When using Node.js 24 or later, Node.js\
      \ can automatically detect if a ``.js`` file should be treated as CommonJS or\
      \ as an ES module. To enable auto-detection, add the ``--experimental-detect-module``\
      \ flag to the ``NODE_OPTIONS`` environment variable. For more information, see\
      \ [Experimental Node.js features](https://docs.aws.amazon.com//lambda/latest/dg/lambda-nodejs.html#nodejs-experimental-features).\n\
      \   For JSON, you must escape quotes and special characters such as newline\
      \ (``\\n``) with a backslash.\n If you specify a function that interacts with\
      \ an AWS CloudFormation custom resource, you don't have to write your own functions\
      \ to send responses to the custom resource that invoked the function. AWS CloudFormation\
      \ provides a response module ([cfn-response](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html))\
      \ that simplifies sending responses. See [Using Lambda with CloudFormation](https://docs.aws.amazon.com/lambda/latest/dg/services-cloudformation.html)\
      \ for details."
  LambdaFunctionDevimpressicolambdaCodeZipFileNK8Rm:
    NoEcho: "true"
    Type: "String"
    Description:
      "(Node.js and Python) The source code of your Lambda function. If\
      \ you include your function source inline with this parameter, CFN places it\
      \ in a file named ``index`` and zips it to create a [deployment package](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-package.html).\
      \ This zip file cannot exceed 4MB. For the ``Handler`` property, the first part\
      \ of the handler identifier must be ``index``. For example, ``index.handler``.\n\
      \  When you specify source code inline for a Node.js function, the ``index``\
      \ file that CFN creates uses the extension ``.js``. This means that Node.js\
      \ treats the file as a CommonJS module.\n When using Node.js 24 or later, Node.js\
      \ can automatically detect if a ``.js`` file should be treated as CommonJS or\
      \ as an ES module. To enable auto-detection, add the ``--experimental-detect-module``\
      \ flag to the ``NODE_OPTIONS`` environment variable. For more information, see\
      \ [Experimental Node.js features](https://docs.aws.amazon.com//lambda/latest/dg/lambda-nodejs.html#nodejs-experimental-features).\n\
      \   For JSON, you must escape quotes and special characters such as newline\
      \ (``\\n``) with a backslash.\n If you specify a function that interacts with\
      \ an AWS CloudFormation custom resource, you don't have to write your own functions\
      \ to send responses to the custom resource that invoked the function. AWS CloudFormation\
      \ provides a response module ([cfn-response](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html))\
      \ that simplifies sending responses. See [Using Lambda with CloudFormation](https://docs.aws.amazon.com/lambda/latest/dg/services-cloudformation.html)\
      \ for details."
  LambdaFunctionASGTerminationBackupCodeS3Key1Kba8:
    NoEcho: "true"
    Type: "String"
    Description: "The Amazon S3 key of the deployment package."
  LambdaFunctionASGTerminationBackupCodeSourceKMSKeyArnV9OJp:
    NoEcho: "true"
    Type: "String"
    Description:
      "The ARN of the KMSlong (KMS) customer managed key that's used to\
      \ encrypt your function's .zip deployment package. If you don't provide a customer\
      \ managed key, Lambda uses an [owned key](https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#aws-owned-cmk)."
Resources:
  LambdaPermissionFunctionASGTerminationBackup:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Lambda::Permission"
    DeletionPolicy: "Retain"
    Properties:
      FunctionName: "arn:aws:lambda:ap-south-1:313686187887:function:ASGTerminationBackup"
      Action: "lambda:InvokeFunction"
      SourceArn: "arn:aws:events:ap-south-1:313686187887:rule/ASGTerminationBackup-rule"
      Principal: "events.amazonaws.com"
  LambdaFunctionASGTerminationBackup:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Retain"
    Properties:
      MemorySize: 512
      Description: ""
      TracingConfig:
        Mode: "PassThrough"
      Timeout: 603
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "lambda_function.lambda_handler"
      Code:
        SourceKMSKeyArn:
          Ref: "LambdaFunctionASGTerminationBackupCodeSourceKMSKeyArnV9OJp"
        S3ObjectVersion:
          Ref: "LambdaFunctionASGTerminationBackupCodeS3ObjectVersionDfNMe"
        S3Bucket:
          Ref: "LambdaFunctionASGTerminationBackupCodeS3Buckettpomx"
        ZipFile:
          Ref: "LambdaFunctionASGTerminationBackupCodeZipFilenMJG1"
        ImageUri:
          Ref: "LambdaFunctionASGTerminationBackupCodeImageUri6HGXP"
        S3Key:
          Ref: "LambdaFunctionASGTerminationBackupCodeS3Key1Kba8"
      Role: "arn:aws:iam::313686187887:role/ASGTerminationBackup-role"
      FileSystemConfigs: []
      FunctionName: "ASGTerminationBackup"
      Runtime: "python3.12"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/ASGTerminationBackup"
      RecursiveLoop: "Terminate"
      Environment:
        Variables:
          DB_NAME: "testdb"
          DB_PASSWORD: "password"
          SLACK_WEBHOOK_URL: ""
      EphemeralStorage:
        Size: 10240
      Tags:
        - Value: "vansh.padia"
          Key: "CreatedBy"
        - Value: "2026-06-03T13:14:04Z"
          Key: "CreatedAt"
      Architectures:
        - "x86_64"
  EventsRuleRuledevimpressicoeventRule:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Events::Rule"
    DeletionPolicy: "Retain"
    Properties:
      EventBusName: "default"
      EventPattern:
        detail-type:
          - "EC2 Instance-terminate Lifecycle Action"
        source:
          - "aws.autoscaling"
        detail:
          LifecycleHookName:
            - "dev-impressico-termination-hook"
          AutoScalingGroupName:
            - "asg-dev-impressico"
      Description: ""
      State: "ENABLED"
      Targets:
        - Arn: "arn:aws:lambda:ap-south-1:313686187887:function:dev-impressico-lambda"
          RoleArn: "arn:aws:iam::313686187887:role/service-role/Amazon_EventBridge_Invoke_Lambda_66294327"
          Id: "Ide7a0c0f6-7263-4420-834c-8300eed75e75"
      Id: "dev-impressico-eventRule"
      Tags:
        - Value: "dev-impressico-eventRule"
          Key: "name"
      Name: "dev-impressico-eventRule"
  IAMRoleASGTerminationBackuprole:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::313686187887:policy/ASGTerminationBackup-policy"
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      MaxSessionDuration: 3600
      RoleName: "ASGTerminationBackup-role"
      Description: "Allows Lambda functions to call AWS services on your behalf."
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
  LambdaFunctionDevimpressicolambda:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Lambda::Function"
    DeletionPolicy: "Retain"
    Properties:
      MemorySize: 128
      Description: ""
      TracingConfig:
        Mode: "PassThrough"
      VpcConfig:
        SecurityGroupIds: []
        SubnetIds: []
        Ipv6AllowedForDualStack: false
      Timeout: 303
      RuntimeManagementConfig:
        UpdateRuntimeOn: "Auto"
      Handler: "lambda_function.lambda_handler"
      Code:
        SourceKMSKeyArn:
          Ref: "LambdaFunctionDevimpressicolambdaCodeSourceKMSKeyArnabMyW"
        S3ObjectVersion:
          Ref: "LambdaFunctionDevimpressicolambdaCodeS3ObjectVersione07Si"
        S3Bucket:
          Ref: "LambdaFunctionDevimpressicolambdaCodeS3BucketYWBwK"
        ZipFile:
          Ref: "LambdaFunctionDevimpressicolambdaCodeZipFileNK8Rm"
        ImageUri:
          Ref: "LambdaFunctionDevimpressicolambdaCodeImageUriJrShB"
        S3Key:
          Ref: "LambdaFunctionDevimpressicolambdaCodeS3Keyu3jbz"
      Role: "arn:aws:iam::313686187887:role/dev-impressico-lambda-execution-role"
      FileSystemConfigs: []
      FunctionName: "dev-impressico-lambda"
      Runtime: "python3.14"
      PackageType: "Zip"
      LoggingConfig:
        LogFormat: "Text"
        LogGroup: "/aws/lambda/dev-impressico-lambda"
      RecursiveLoop: "Terminate"
      Environment:
        Variables:
          DB_NAME: "testdb"
          DB_PASSWORD: "password"
          SLACK_WEBHOOK_URL: ""
      EphemeralStorage:
        Size: 512
      Tags:
        - Value: "vansh.padia"
          Key: "CreatedBy"
        - Value: "2026-06-02T09:07:00Z"
          Key: "CreatedAt"
      Architectures:
        - "x86_64"
  LambdaPermissionFunctiondevimpressicolambda:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Lambda::Permission"
    DeletionPolicy: "Retain"
    Properties:
      FunctionName: "arn:aws:lambda:ap-south-1:313686187887:function:dev-impressico-lambda"
      Action: "lambda:InvokeFunction"
      SourceArn: "arn:aws:events:ap-south-1:313686187887:rule/dev-impressico-eventRule"
      Principal: "events.amazonaws.com"
  EventsRuleRuleASGTerminationBackuprule:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Events::Rule"
    DeletionPolicy: "Retain"
    Properties:
      EventBusName: "default"
      EventPattern:
        detail-type:
          - "EC2 Instance-terminate Lifecycle Action"
        source:
          - "aws.autoscaling"
        detail:
          AutoScalingGroupName:
            - "asg-dev-impressico"
      State: "ENABLED"
      Targets:
        - Arn: "arn:aws:lambda:ap-south-1:313686187887:function:ASGTerminationBackup"
          Id: "33w2owcuzdw8dfr677"
      Id: "ASGTerminationBackup-rule"
      Tags: []
      Name: "ASGTerminationBackup-rule"
  IAMRoleAmazonEventBridgeInvokeLambda66294327:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/service-role/"
      ManagedPolicyArns:
        - "arn:aws:iam::313686187887:policy/service-role/Amazon_EventBridge_Invoke_Lambda_66294327"
      MaxSessionDuration: 3600
      RoleName: "Amazon_EventBridge_Invoke_Lambda_66294327"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Condition:
              StringEquals:
                aws:SourceAccount: "313686187887"
                aws:SourceArn: "arn:aws:events:ap-south-1:313686187887:rule/dev-impressico-eventRule"
            Action: "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service: "events.amazonaws.com"
            Sid: "TrustEventBridgeService"
